src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Bundle\FrameworkBundle\CacheWarmer\SerializerCacheWarmer;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
const ROLE_ADMIN = 'admin';
const ROLE_ADMIN_CODE = 3;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;


    /**
     * @ORM\Column(type="string")
     *
     * @Assert\NotBlank(message="Please, upload your avatar as a png/jpeg file.")
     * @Assert\File(mimeTypes={ "image/png" })
     */
    private $avatar;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\MaritalStatus", cascade={"persist", "remove"})
     */
    private $marital_id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Role", cascade={"persist", "remove"})
     */
    private $role;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getAvatar()
    {
        return $this->avatar;
    }

    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getMaritalId(): ?MaritalStatus
    {
        return $this->marital_id;
    }

    public function setMaritalId(?MaritalStatus $marital_id): self
    {
        $this->marital_id = $marital_id;

        return $this;
    }


    public function getRoles()
    {

        return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized, array('allowed_classes' => false));
    }


    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }


    public function isAdminRole()
    {

        $checkRole = $this->role->getId();
        return $this->checkAdmin($checkRole);
    }

    protected function checkAdmin($role)
    {

        return $role === ROLE_ADMIN_CODE ? true : false;

    }


    public function isAdmin($role)
    {

        return $this->statusCheck(ROLE_ADMIN, $role);
    }

    protected function statusCheck($status, $role)
    {

        return $role === $status ? true : false;

    }


    public function checkBirthday()
    {

        $birthDate = $this->birthday->format('d-m-Y');
        $time = strtotime($birthDate);


        if(date('m-d') == date('m-d',$time)) {
            return true;
        }else{
            return false;
        }
    }


}

src/Entity/UserSkill.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserSkillRepository")
 */
class UserSkill
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User" )
     * @ORM\JoinColumn(name="user_id_id", referencedColumnName="id")
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Skill")
     * @ORM\JoinColumn(name="skill_id_id", referencedColumnName="id")
     */
    private $skill_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?user
    {
        return $this->user_id;
    }

    public function setUserId(?user $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getSkillId(): ?skill
    {
        return $this->skill_id;
    }

    public function setSkillId(?skill $skill_id): self
    {
        $this->skill_id = $skill_id;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\MaritalStatus;
use App\Entity\Role;
use App\Entity\Skill;
use App\Entity\UserSkill;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Exporter\Handler;
use Exporter\Source\PDOStatementSourceIterator;
use Exporter\Writer\CsvWriter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\HttpFoundation\File\File;

class UserController extends Controller
{
    private $entityManager;
    private $encoder;
    private $userRepo;
    private $skillRepo;
    private $userSkillRepo;
    private $maritalStatusRepo;
    private $roleRepo;
    private $security;

    /**
     * UserController constructor.
     */
    public function __construct(UserPasswordEncoderInterface $encoder, Security $security , EntityManagerInterface $entityManager)
    {
        $this->encoder = $encoder;
        $this->entityManager = $entityManager;
        $this->userRepo = $entityManager->getRepository(User::class);
        $this->skillRepo = $entityManager->getRepository(Skill::class);
        $this->userSkillRepo = $entityManager->getRepository(UserSkill::class);
        $this->maritalStatusRepo = $entityManager->getRepository(MaritalStatus::class);
        $this->roleRepo = $entityManager->getRepository(Role::class);
        $this->security = $security;

    }


    /**
     * @Route("/user/dashboard", name="user_dashboard")
     */
    public function dashboard()
    {
        $loggedUser = $this->security->getUser();
        //   $loggedUser = $this->get('security.token_storage')->getToken()->getUser();

        if ($loggedUser->isAdminRole()) {
            $users = $this->userRepo->findAll();


        } else {
            $users = $this->userRepo->findByUserID($loggedUser->getId());

        }

        $userSkills = $this->userSkillRepo->findAll();



        return $this->render('user/dashboard.html.twig', ['users' => $users, 'userSkills' => $userSkills]);
    }


    /**
     * Call this method to get singleton
     *
     * @return User
     */
    public static function InstanceUser()
    {
        static $inst = null;
        if ($inst === null) {
            $inst = new User();
        }
        return $inst;
    }


    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    /**
     *
     * @Route("/user/edit/{id}", name="user_edit")
     */
    public function edit($id)
    {

        $marital_list = $this->maritalStatusRepo->findAll();
        $roles = $this->roleRepo->findAll();
        $skills = $this->skillRepo->findAll();

        if ($id == 0) {
            $user = new User;
            $userSkills = 0;

        } else {
            $user = $this->userRepo->find($id);
            $userSkills = $this->userSkillRepo->findByUser($user->getId());
        }
        return $this->render('user/edit.html.twig', ['user' => $user, 'skills' => $skills, 'roles' => $roles, "marital_list" => $marital_list, 'userSkills' => $userSkills]);
    }


    /**
     * @Route("/user/update", name="user_update")
     */
    public function update(Request $request)
    {

        $loggedUser = $this->security->getUser();

        $code = $request->get('code');

        if ($code == 0 || $code == null) {

            $user = new User();
            $user->setUsername($request->get('username'));

            $plainPassword = $request->get('password');
            $encoded = $this->encoder->encodePassword($user, $plainPassword);

            $user->setPassword($encoded);

        } else {
            $user = $this->userRepo->find($code);

        }


        $file = $request->files->get("avatar");
        if ($file != null) {
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
            $file->move(
                $this->getParameter('upload_directory'),
                $fileName
            );

            $user->setAvatar($fileName);
        }

        $user->setName($request->get('name'));
        $user->setSurname($request->get('surname'));
        $user->setCountry($request->get('country'));


        $date = new \DateTime($request->get('birthday'));
        $user->setBirthday($date);

        $maritalID = $request->get('marital');
        $marital = $this->maritalStatusRepo->find($maritalID);
        $user->setMaritalId($marital);

        if ($loggedUser->isAdminRole()) {
            $roleID = $request->get('role');
            $role = $this->roleRepo->find($roleID);
            $user->setRole($role);
        }

        $this->entityManager->persist($user);
        $this->entityManager->flush();

        //skill selected by user into the view
        $selectedSkills = $request->get('skills');

        if ($selectedSkills != null) {

            $allPersonalSkill = $this->userSkillRepo->findByUser($user->getId());
            foreach ($allPersonalSkill as $ps){
                if (!in_array($ps->getSkillId()->getId(), $selectedSkills))
                {
                    $this->entityManager->remove($ps);
                    $this->entityManager->flush();
                }

            }

            foreach ($selectedSkills as $s) {

                //create instance of skill using $s single element
                $skill = $this->skillRepo->find($s);


//                check if the skill is already saved on DB
                $personalSkill = $this->userSkillRepo->findByUserSkill($user->getId(),$skill->getId());

                if ($personalSkill == null) {

                    $us = new UserSkill();
                    $us->setUserId($user);
                    $us->setSkillId($skill);
                    $this->entityManager->persist($us);
                    $this->entityManager->flush();


                }
            }

        }

        $this->addFlash(
            'notice',
            'The user ' . $user->getName() .' ' . $user->getSurname().' has correctly been updated'
        );
        return $this->redirectToRoute('user_dashboard');


    }


    /**
     * @Route("/user/userSearch", name="user_search")
     */
    public function userSearch(Request $request)
    {
        $query = $request->get('query');

        $users = $this->userRepo->findByNameSurname($query);
        $userSkills = $this->userSkillRepo->findAll();

        return $this->render('user/search.html.twig', ['users' => $users, "userSkills" => $userSkills]);
    }

    /**
     * @Route("/user/paramSearch/{code}", name="param_search")
     */
    public function paramSearch($code)
    {
        $users = $this->userSkillRepo->findBySkill($code);
        return $this->render('user/paramSearch.html.twig', ['users' => $users]);
    }


    /**
     * @Route("/user/exportCSV/", name="export_csv")
     */
    public function exportCSV()
    {
        $users = $this->userRepo->findAll();

// Prepare the data source

        $dbh = new \PDO('mysql://root@127.0.0.1:3306/employeeManagerdb');
        $stm = $dbh->prepare('SELECT id, username, name FROM user');
        $stm->execute();

        $source = new PDOStatementSourceIterator($stm);

// Prepare the writer
        $writer = new CsvWriter('file\data.csv');

// Export the data
        Handler::create($source, $writer)->export();

        return true;
    }



    /**
     * @Route("/user/deleteUser", name="user_delete")
     */
    public function deleteUser(Request $request)
    {


        $code = $request->get('id');


        $user = $this->userRepo->find($code);



        //remove skill on table userskill into db
        $personalSkills = $this->userSkillRepo->findByUser($user->getId());
        foreach ($personalSkills as $ps) {
            $this->entityManager->remove($ps);
            $this->entityManager->flush();
        }
        $user->setRole(null);
        $user->setMaritalId(null);

        $this->entityManager->remove($user);
        $this->entityManager->flush();

        $data = 1;

        return new JsonResponse($data);

    }


    /**
     * @Route("/user/demo", name="user_demo")
     */
    public function demo()
    {
        if ($this->container->get('security.authorization_checker')->isGranted('ROLE_USER')) {
            var_dump("ciao");
            die;


        } else if ($this->container->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            var_dump("ciao Admin");
            die;


        }
        return new JsonResponse(0);

    }

//
//    /**
//     * @Route("/user/addUser", name="add_user")
//     */
//    public function addUser()
//    {
//
//
//        $entityManager = $this->getDoctrine()->getManager();
//
//        $user = new User();
//        $user->setUsername("admin");
//
//        $plainPassword = "admin";
//        $encoded = $this->encoder->encodePassword($user, $plainPassword);
//        $user->setPassword($encoded);
//
//        $user->setName("Mauricio");
//        $user->setSurname("Mauricio");
//
//        $date = new \DateTime("10/10/2000");
//        $user->setBirthday($date);
//
//
//        $entityManager->persist($user);
//        $entityManager->flush();
//
//        return $this->redirectToRoute('index');
//    }

}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}


    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                {% if (user.id is not null or user.id != 0) %}
                                    <h4>Edit user {{ user.name ~ " " ~ user.surname }}</h4>
                                {% else %}
                                    <h4>Add a new user</h4>
                                {% endif %}
                                <hr>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">


                                <form action="{{ path('user_update') }}" method="post" enctype="multipart/form-data">

                                    <input type="hidden" name="code"
                                           value=" {% if (user.id is not null) %} {{ user.id }}{% else %} 0 {% endif %}">

                                    <div class="form-group row">
                                        <label for="avatar" class="col-4 col-form-label">Avatar</label>
                                        <div class="col-5">
                                            <div class="input-group mb-3">
                                                <label for="avatar">Choose your avatar</label>
                                                <input type="file" class="form-control-file" id="avatar" name="avatar">
                                            </div>
                                        </div>
                                        <div class="col-3">
                                            {% if(user.avatar is empty) %}
                                                <img src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" width="100"
                                                     class="img-circle ">

                                            {% else %}
                                                <img src="{{ asset('uploads/'~ user.avatar ) }}" width="100"
                                                     class="img-circle ">

                                            {% endif %}
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="name" class="col-4 col-form-label">Name *</label>
                                        <div class="col-8">
                                            <input id="name" name="name" placeholder="Name..."
                                                   value="{{ (user.id is not null ) ? user.name  :'' }}"
                                                   class="form-control here" required="required" type="text">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="surname" class="col-4 col-form-label">Surname *</label>
                                        <div class="col-8">
                                            <input id="surname" name="surname" placeholder="Surname..."
                                                   value="{{ (user.id is not null ) ? user.surname  :'' }}"
                                                   required="required"
                                                   class="form-control here" type="text">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="username" class="col-4 col-form-label">Username *</label>
                                        <div class="col-8">
                                            <input id="username" name="username" placeholder="Username..."
                                                   value="{{ (user.id is not null ) ? user.username  :'' }}"
                                                    {{ (user.id == 0 ) ? '' : 'readonly="readonly"' }}
                                                   class="form-control here" type="text">
                                        </div>
                                    </div>

                                    {% if (user.id == 0) %}
                                        <div class="form-group row">
                                            <label for="password" class="col-4 col-form-label">Password</label>
                                            <div class="col-8">
                                                <input id="password" name="password"
                                                       placeholder="Enter a new Password..."
                                                       class="form-control here" type="password">
                                            </div>
                                        </div>
                                    {% endif %}


                                    <div class="form-group row">
                                        <label for="birthday" class="col-4 col-form-label">Birthday</label>
                                        <div class="col-8">
                                            <input id="birthday" name="birthday" placeholder="Birthday..."
                                                   value="{{ (user.id is not null ) ? user.birthday.format('d-m-Y ') :'' }}"
                                                   class="form-control here datepicker" type="text">
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label for="country" class="col-4 col-form-label">Country</label>
                                        <div class="col-8">
                                            <input id="country" name="country" placeholder="Country..."
                                                   value="{{ (user.id is not null ) ? user.country  :'' }}"
                                                   class="form-control here" type="text">
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label for="role" class="col-4 col-form-label">Marital Status</label>
                                        <div class="col-8">
                                            <select id="marital" name="marital" class="custom-select">
                                                {% if user.id is not empty %}
                                                    {% for m in marital_list %}
                                                        <option value="{{ m.id }}" {{ m.id == user.maritalId.id  ? ' selected ' : "" }}>
                                                            {{ m.name }}
                                                        </option>
                                                    {% endfor %}
                                                {% else %}
                                                    {% for m in marital_list %}
                                                        <option value="{{ m.id }}">
                                                            {{ m.name }}
                                                        </option>
                                                    {% endfor %}
                                                {% endif %}
                                            </select>
                                        </div>
                                    </div>

                                    {% if (app.user.isAdminRole()) %}

                                        <div class="form-group row">
                                            <label for="role" class="col-4 col-form-label">User Role</label>
                                            <div class="col-8">
                                                <select id="role" name="role" class="custom-select">
                                                    {% if user.id is not empty %}

                                                        {% for r in roles %}
                                                            <option value="{{ r.id }}" {{ r.id == user.role.id  ? ' selected ' : "" }}>
                                                                {{ r.name }}
                                                            </option>
                                                        {% endfor %}
                                                    {% else %}
                                                        {% for r in roles %}
                                                            <option value="{{ r.id }}">
                                                                {{ r.name }}
                                                            </option>
                                                        {% endfor %}
                                                    {% endif %}
                                                </select>
                                            </div>
                                        </div>

                                    {% endif %}


                                    <div class="form-group row">
                                        <label for="role" class="col-4 col-form-label">Skills</label>
                                        <div class="col-8">

                                            <select class="js-example-basic-multiple custom-select" name="skills[]"
                                                    multiple="multiple">
                                                {% for s in skills %}
                                                    <option value="{{ s.id }}">
                                                        {{ s.name }}
                                                    </option>
                                                {% endfor %}
                                            </select>

                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <div class="offset-4 col-8">
                                            <button name="submit" type="submit" class="btn btn-primary">
                                                {% if (user.id is not null) %}
                                                    Edit user
                                                {% else %}
                                                    Add a new user
                                                {% endif %}

                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

    <script type="text/javascript">


        $(document).ready(function () {
            $('.datepicker').datepicker({
                autoclose: true,
                format: 'dd-mm-yyyy',
            });
        });


        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();


            var skills = [];
            {% for us in userSkills %}
            skills.push({{ us.skillId.id }});
            {% endfor %}
            console.log("selected values: ", skills);


                $('.js-example-basic-multiple').select2({}).select2('val', [skills]);


        });

    </script>
{% endblock %}